Repository 9oormthonUNIV-3th-KGU/family-note-ui, pull requests merged in 2024-09, with the labels that each got.

#3 [Feat] Login Screen
  package-lock.json
  package.json
  src/assets/images/left-bottom.svg
  src/assets/images/left-top.svg
  src/assets/images/logo.svg
  src/assets/images/right-bottom.svg
  src/assets/images/right-top.svg
  src/components/Background.tsx
  src/components/LoginForm.tsx
  src/components/TextButton.tsx
  src/main.tsx
  src/pages/Auth.tsx
Labels: enhancement

#7 [FEAT] create search screen with popup
  package.json
  pnpm-lock.yaml
  src/components/Background.tsx
  src/components/FamilySheet.tsx
  src/components/ListItem.tsx
  src/components/Popup.tsx
  src/components/SearchBar.tsx
  src/components/TextButton.tsx
  src/main.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/pages/search.tsx
  src/stores/usePopupStore.ts
  src/stores/useSearchStore.ts
Labels: enhancement

#10 [FIX] Resolve answer mismatch
  src/components/AnswerBox.tsx
  src/components/AnswerModal.tsx
  src/components/GetQuestionBtn.tsx
  src/components/QuestionBox.tsx
  src/pages/home.tsx
  src/services/FamilyAnswerApi.ts
  src/services/GetFamilyAnswerApi.ts
  src/services/GetFamilyApi.ts
  src/services/GetFamilyQuestionApi.ts
  src/stores/UseAnswerModalStore.ts
  src/stores/UseQuestionStore.ts
  src/utils/ UserToken.ts
  src/utils/FormatDate.ts
Labels: bug, enhancement

#13 Feat/auth service
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/LoginForm.tsx
  src/components/RegisterForm.tsx
  src/components/TextButton.tsx
  src/config/api-client.ts
  src/context/AuthContext.tsx
  src/hooks/useAuthContext.ts
  src/hooks/useLogin.ts
  src/hooks/useRegister.ts
  src/main.tsx
  src/model/AuthRequest.ts
  src/model/AuthResponse.ts
  src/model/Profile.ts
  src/model/ProfileResponse.ts
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/services/auth-service.ts
  src/validation/profileValidationSchema.ts
Labels: enhancement

#14 Fetch new question, Control GetQuestionBtn state
  src/components/AnswerModal.tsx
  src/components/GetQuestionBtn.tsx
  src/components/Header.tsx
  src/components/LogoutBtn.tsx
  src/model/FamilyAnswer.ts
  src/model/FamilyAnswerResponse.ts
  src/pages/home.tsx
  src/services/FamilyAnswerApi.ts
  src/services/GetFamilyAnswerApi.ts
  src/services/GetFamilyApi.ts
  src/services/GetFamilyQuestionApi.ts
  src/stores/UseGetQuestionBtnStore.ts
  src/stores/UseQuestionStore.ts
  src/utils/UserToken.ts
Labels: enhancement

#16 [Feat] Fetch Family List
  src/assets/images/logo_horizontal.png
  src/components/FamilyBox.tsx
  src/components/FamilyInfoBox.tsx
  src/components/FamilyListBox.tsx
  src/components/GotoSearchBtn.tsx
  src/components/Header.tsx
  src/components/LogoutBtn.tsx
  src/main.tsx
  src/pages/Select.tsx
  src/pages/home.tsx
  src/services/GetFamilyListApi.ts
  src/services/GetFamilyQuestionApi.ts
  src/stores/UseFamilyStore.ts
  src/utils/UserToken.ts
Labels: enhancement

#19 [FEAT] search and create family
  src/components/FamilySheet.tsx
  src/components/LoginForm.tsx
  src/components/Popup.tsx
  src/components/ProfileCard.tsx
  src/components/RegisterForm.tsx
  src/components/SearchBar.tsx
  src/config/api-client.ts
  src/hooks/useFamilyCreate.ts
  src/hooks/useLogin.ts
  src/hooks/useProfiles.ts
  src/hooks/useRegister.ts
  src/main.tsx
  src/model/FamilyCreateRequest.ts
  src/model/FamilyCreateResponse.ts
  src/model/ProfileResponse.ts
  src/services/family-service.ts
  src/stores/useCurrentUserStore.ts
  src/stores/userProfileStore.ts
  src/validation/familyNameValidationSchema.ts
Labels: enhancement

#22 [FIX] remove unused values
  src/components/FamilySheet.tsx
  src/components/LoginForm.tsx
  src/components/Popup.tsx
  src/components/RegisterForm.tsx
  src/pages/Register.tsx
Labels: bug
